#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    files = bld.path.ant_glob('*.obj')

    for file in files:
        filename = str(file)

        bld.install_files('${PACKAGE_DATADIR}/objects', filename)
